// types.js
export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const CREATE_POST_COMMENT = 'CREATE_POST_COMMENT';
