# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Set default docker image with node
defaults: &defaults
  docker:
    - image: circleci/node:12.14.1

# Configure jobs which use default node docker image
jobs:
  build:
    <<: *defaults
    description: "Run linter and cache node modules"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install root dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: ESLint
          command: yarn lint

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  # Name the workflow "build"
  build:
    # Run the build job in its own container
    jobs:
      - build

